### ISSUE TITLE
I can't get this to work !?

### ISSUE THREAD

**Issue by drupalshift** [ykh/rtl-happy#8]
Hi there,
I tried extension in developer mode with Chrome 61 but doesn't work, 
It's getting added to Chrome Toolbar but tried with Phabricator and Trello! no luck 

This is the first time that I'm trying to use this, Is there any configuration that I have to change or apply ?

**Comment by ykh** [comment]
Hi Hamed :)
I just tested it right now and it works fine.
My steps:
1- Go to 'manage extesnions' from your Chrome.
2- Enable developer mode.
3- Click on 'Load unpacked extension'.
4- Select this directory: `<rtl-happy-project-directory>/dist/extension`
5- It's added to my extensions and works fine in Trello & Phabricator.

Tell me the result...

**Comment by drupalshift** [comment]
It has some conflicts with my addons config ( Ghostery ) 
Thanks for your hard work, Awesome addon
